__impl_tuple_zip!(A, B, C, D, E, F | Z);
__impl_tuple_zip!(A, B, C, D, E, F, G | Z);
__impl_tuple_zip!(A, B, C, D, E, F, G, H | Z);
__impl_tuple_zip!(A, B, C, D, E, F, G, H, I | Z);
__impl_tuple_zip!(A, B, C, D, E, F, G, H, I, J | Z);

__impl_tuple_insert!(A, B, C, D, E, F | Z);
__impl_tuple_insert!(A, B, C, D, E, F, G | Z);
__impl_tuple_insert!(A, B, C, D, E, F, G, H | Z);
__impl_tuple_insert!(A, B, C, D, E, F, G, H, I | Z);
__impl_tuple_insert!(A, B, C, D, E, F, G, H, I, J | Z);

__impl_tuple_insert_exact!(A, B, C, D, E, F | Z at 0 => Z, A, B, C, D, E, F);
__impl_tuple_insert_exact!(A, B, C, D, E, F | Z at 1 => A, Z, B, C, D, E, F);
__impl_tuple_insert_exact!(A, B, C, D, E, F | Z at 2 => A, B, Z, C, D, E, F);
__impl_tuple_insert_exact!(A, B, C, D, E, F | Z at 3 => A, B, C, Z, D, E, F);
__impl_tuple_insert_exact!(A, B, C, D, E, F | Z at 4 => A, B, C, D, Z, E, F);
__impl_tuple_insert_exact!(A, B, C, D, E, F | Z at 5 => A, B, C, D, E, Z, F);
__impl_tuple_insert_exact!(A, B, C, D, E, F | Z at 6 => A, B, C, D, E, F, Z);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G | Z at 0 => Z, A, B, C, D, E, F, G);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G | Z at 1 => A, Z, B, C, D, E, F, G);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G | Z at 2 => A, B, Z, C, D, E, F, G);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G | Z at 3 => A, B, C, Z, D, E, F, G);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G | Z at 4 => A, B, C, D, Z, E, F, G);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G | Z at 5 => A, B, C, D, E, Z, F, G);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G | Z at 6 => A, B, C, D, E, F, Z, G);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G | Z at 7 => A, B, C, D, E, F, G, Z);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 0 => Z, A, B, C, D, E, F, G, H);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 1 => A, Z, B, C, D, E, F, G, H);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 2 => A, B, Z, C, D, E, F, G, H);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 3 => A, B, C, Z, D, E, F, G, H);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 4 => A, B, C, D, Z, E, F, G, H);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 5 => A, B, C, D, E, Z, F, G, H);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 6 => A, B, C, D, E, F, Z, G, H);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 7 => A, B, C, D, E, F, G, Z, H);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H | Z at 8 => A, B, C, D, E, F, G, H, Z);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 0 => Z, A, B, C, D, E, F, G, H, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 1 => A, Z, B, C, D, E, F, G, H, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 2 => A, B, Z, C, D, E, F, G, H, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 3 => A, B, C, Z, D, E, F, G, H, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 4 => A, B, C, D, Z, E, F, G, H, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 5 => A, B, C, D, E, Z, F, G, H, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 6 => A, B, C, D, E, F, Z, G, H, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 7 => A, B, C, D, E, F, G, Z, H, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 8 => A, B, C, D, E, F, G, H, Z, I);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I | Z at 9 => A, B, C, D, E, F, G, H, I, Z);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 0 => Z, A, B, C, D, E, F, G, H, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 1 => A, Z, B, C, D, E, F, G, H, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 2 => A, B, Z, C, D, E, F, G, H, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 3 => A, B, C, Z, D, E, F, G, H, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 4 => A, B, C, D, Z, E, F, G, H, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 5 => A, B, C, D, E, Z, F, G, H, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 6 => A, B, C, D, E, F, Z, G, H, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 7 => A, B, C, D, E, F, G, Z, H, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 8 => A, B, C, D, E, F, G, H, Z, I, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 9 => A, B, C, D, E, F, G, H, I, Z, J);
__impl_tuple_insert_exact!(A, B, C, D, E, F, G, H, I, J | Z at 10 => A, B, C, D, E, F, G, H, I, J, Z);

__impl_tuple_remove!(A, B, C, D, E, F);
__impl_tuple_remove!(A, B, C, D, E, F, G);
__impl_tuple_remove!(A, B, C, D, E, F, G, H);
__impl_tuple_remove!(A, B, C, D, E, F, G, H, I);
__impl_tuple_remove!(A, B, C, D, E, F, G, H, I, J);

__impl_tuple_remove_exact!(A, B, C, D, E, F at 0 => B, C, D, E, F);
__impl_tuple_remove_exact!(A, B, C, D, E, F at 1 => A, C, D, E, F);
__impl_tuple_remove_exact!(A, B, C, D, E, F at 2 => A, B, D, E, F);
__impl_tuple_remove_exact!(A, B, C, D, E, F at 3 => A, B, C, E, F);
__impl_tuple_remove_exact!(A, B, C, D, E, F at 4 => A, B, C, D, F);
__impl_tuple_remove_exact!(A, B, C, D, E, F at 5 => A, B, C, D, E);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G at 0 => B, C, D, E, F, G);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G at 1 => A, C, D, E, F, G);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G at 2 => A, B, D, E, F, G);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G at 3 => A, B, C, E, F, G);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G at 4 => A, B, C, D, F, G);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G at 5 => A, B, C, D, E, G);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G at 6 => A, B, C, D, E, F);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H at 0 => B, C, D, E, F, G, H);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H at 1 => A, C, D, E, F, G, H);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H at 2 => A, B, D, E, F, G, H);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H at 3 => A, B, C, E, F, G, H);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H at 4 => A, B, C, D, F, G, H);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H at 5 => A, B, C, D, E, G, H);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H at 6 => A, B, C, D, E, F, H);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H at 7 => A, B, C, D, E, F, G);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 0 => B, C, D, E, F, G, H, I);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 1 => A, C, D, E, F, G, H, I);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 2 => A, B, D, E, F, G, H, I);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 3 => A, B, C, E, F, G, H, I);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 4 => A, B, C, D, F, G, H, I);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 5 => A, B, C, D, E, G, H, I);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 6 => A, B, C, D, E, F, H, I);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 7 => A, B, C, D, E, F, G, I);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I at 8 => A, B, C, D, E, F, G, H);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 0 => B, C, D, E, F, G, H, I, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 1 => A, C, D, E, F, G, H, I, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 2 => A, B, D, E, F, G, H, I, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 3 => A, B, C, E, F, G, H, I, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 4 => A, B, C, D, F, G, H, I, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 5 => A, B, C, D, E, G, H, I, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 6 => A, B, C, D, E, F, H, I, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 7 => A, B, C, D, E, F, G, I, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 8 => A, B, C, D, E, F, G, H, J);
__impl_tuple_remove_exact!(A, B, C, D, E, F, G, H, I, J at 9 => A, B, C, D, E, F, G, H, I);

__impl_tuple_concat!(A, B, C, D, E, F with G);
__impl_tuple_concat!(A, B, C, D, E, F with G, H);
__impl_tuple_concat!(A, B, C, D, E, F with G, H, I);
__impl_tuple_concat!(A, B, C, D, E, F with G, H, I, J);
__impl_tuple_concat!(A, B, C, D, E, F, G with H);
__impl_tuple_concat!(A, B, C, D, E, F, G with H, I);
__impl_tuple_concat!(A, B, C, D, E, F, G with H, I, J);
__impl_tuple_concat!(A, B, C, D, E, F, G, H with I);
__impl_tuple_concat!(A, B, C, D, E, F, G, H with I, J);
__impl_tuple_concat!(A, B, C, D, E, F, G, H, I with J);
